# Generated by Django 5.1 on 2024-08-26 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_created_at"),
        ("users", "0004_alter_user_email_alter_user_name"),
    ]

    operations = []
