# Generated by Django 5.1 on 2024-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(default="", max_length=255),
        ),
    ]
