# Generated by Django 5.1 on 2024-08-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(max_length=255, null=True),
        ),
    ]
