services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        - DEV=false
    ports:
      - "8000:8000"
    volumes:
      - ./customk:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
