services:
  app:
    build: .
    image: ${NCP_CONTAINER_REGISTRY}/customk-app:latest
    command: sh ./scripts/start-deploy.sh
    volumes:
      - ./customk:/app
      - static-data:/vol/web
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    image: ${NCP_CONTAINER_REGISTRY}/customk-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-data:/vol/web
    depends_on:
      - app

volumes:
  static-data: