services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV: "true"
    command: sh ./scripts/start-dev.sh
    volumes:
      - ./customk:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localdb
      - DB_NAME=testdb
      - DB_USER=rbwo
      - DB_PASS=password123
    env_file:
      - .env
    depends_on:
      - localdb

  localdb:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=rbwo
      - POSTGRES_PASSWORD=password123
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: