services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./customk:/app
    command: >
      sh -c "
      mypy . &&
      python manage.py runserver 0.0.0.0:8000
      "
