# Generated by Django 5.1 on 2024-08-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image_url',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
