# Generated by Django 5.1 on 2024-09-06 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = []
