# Generated by Django 5.1 on 2024-09-06 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_auto_20240906_1518"),
    ]

    operations = []
