# Generated by Django 5.1 on 2024-09-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_rename_notification_paymentnotification_and_more"),
        ("payments", "0002_payment_refunded_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentnotification",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.payment",
            ),
        ),
    ]
