# Generated by Django 5.1 on 2024-08-21 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_rename_description_question_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="question",
            new_name="question_id",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="course",
            new_name="class_id",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="user",
            new_name="user_id",
        ),
    ]
