# Generated by Django 5.1 on 2024-08-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_question_answer_question_answer_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer_user_id",
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
