# Generated by Django 5.1 on 2024-08-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
