# Generated by Django 5.1 on 2024-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_class_is_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="classdate",
            name="person",
            field=models.IntegerField(default=0),
        ),
    ]
