# Generated by Django 5.1 on 2024-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0005_alter_class_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
