# Generated by Django 5.1 on 2024-08-21 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0006_exchangerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
