# Generated by Django 5.1 on 2024-08-28 06:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0008_rename_course_classdate_class_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="class_type",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
