# Generated by Django 5.1 on 2024-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0010_alter_classimages_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classimages",
            name="image_url",
            field=models.URLField(max_length=2000),
        ),
    ]
