# Generated by Django 5.1 on 2024-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0013_category_genre_class_category_class_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="address",
            field=models.CharField(
                help_text="주소를 '도, 시, 구' 형식으로 입력해주세요.", max_length=255
            ),
        ),
    ]
