# Generated by Django 5.1 on 2024-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0014_alter_class_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="discount_rate",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
