# Generated by Django 5.1 on 2024-09-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0017_remove_classimages_description_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classimages",
            name="description_image_urls",
        ),
        migrations.RemoveField(
            model_name="classimages",
            name="detail_image_urls",
        ),
        migrations.RemoveField(
            model_name="classimages",
            name="thumbnail_image_urls",
        ),
        migrations.AddField(
            model_name="classimages",
            name="description_image_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="classimages",
            name="detail_image_url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classimages",
            name="thumbnail_image_url",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
