# Generated by Django 5.1 on 2024-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0019_alter_classimages_detail_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classimages",
            name="description_image_url",
        ),
        migrations.RemoveField(
            model_name="classimages",
            name="detail_image_url",
        ),
        migrations.RemoveField(
            model_name="classimages",
            name="thumbnail_image_url",
        ),
        migrations.AddField(
            model_name="classimages",
            name="description_image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="classimages",
            name="detail_image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="classimages",
            name="thumbnail_image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
