# Generated by Django 5.1 on 2024-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0021_alter_class_max_person_alter_class_require_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classdate",
            name="person",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
