# Generated by Django 5.1 on 2024-09-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0022_alter_classdate_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="category",
        ),
        migrations.AlterField(
            model_name="class",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.genre",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="category",
            field=models.ManyToManyField(blank=True, to="classes.category"),
        ),
    ]
