name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run lint and type checks
        run: |
          docker compose -f docker-compose-dev.yml build --build-arg DEV=true
          docker compose run --rm app sh -c "mypy . && ruff check --no-cache && ruff format --no-cache"
