name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run type checks
        run: |
          docker compose run --rm app sh -c "mypy ."

      - name: debug test
        run : |
          docker compose run --rm app sh -c "ls -al"

      - name: Run Ruff format
        run: |
          docker compose run --rm app sh -c "ruff format"

      - name: Run Ruff Check
        run: |
          docker compose run --rm app sh -c "ruff check"

      - name: Run tests
        run: |
          docker compose run --rm app pytest

