name: Customk CI

on: [push]
#  pull_request:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codes
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: package install
        run: poetry install

      - name: Run Luff
        run: |
          poetry run ruff check .

      - name: Run Mypy
        run: |
          poetry run mypy .